import { test, expect } from "@playwright/test"

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem("pictorium_profile_id", "e2e")
    localStorage.setItem("pictorium_profile_stateless", "1")
    localStorage.setItem("pictorium_onboarding_done", "true")
    localStorage.setItem("preferred_lang", "it")
  })
})

for (const width of [390, 1280]) {
  test(`theme picker and light surfaces at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    const errors: string[] = []
    page.on("pageerror", (error) => errors.push(error.message))
    await page.goto("/")
    await expect(page.getByPlaceholder(/cerca/i)).toBeVisible()
    const darkLogoBounds = (await page.locator(".header-logo-dark:visible").first().boundingBox())!
    const trigger = page.getByRole("button", { name: "Tema", exact: true })
    await expect(trigger).toBeVisible()
    expect((await trigger.boundingBox())!.y).toBeLessThan(70)
    await expect(page.getByRole("navigation").getByRole("button", { name: "Tema", exact: true })).toHaveCount(0)
    await expect(page.getByTestId("home-status").getByRole("button", { name: "Tema", exact: true })).toHaveCount(0)
    await trigger.click()
    await expect(page.getByRole("radiogroup", { name: "Tema" })).toBeVisible()
    const menuBounds = (await page.getByRole("radiogroup", { name: "Tema" }).boundingBox())!
    expect(menuBounds.x).toBeGreaterThanOrEqual(0)
    expect(menuBounds.x + menuBounds.width).toBeLessThanOrEqual(width)
    await page.getByRole("radio", { name: "Chiaro", exact: true }).click()
    await expect(page.locator("html")).toHaveAttribute("data-theme", "light")
    const lightLogoBounds = (await page.locator(".header-logo-light:visible").first().boundingBox())!
    expect(lightLogoBounds.width).toBeCloseTo(darkLogoBounds.width, 0)
    expect(lightLogoBounds.height).toBeCloseTo(darkLogoBounds.height, 0)
    await expect(page.getByRole("radiogroup")).toHaveCount(0)
    expect(await page.locator("body").evaluate((el) => getComputedStyle(el).backgroundColor)).toBe("rgb(242, 238, 231)")
    expect(await page.evaluate(() => localStorage.getItem("pictorium_theme"))).toBe("dark")
    expect(await page.evaluate(() => localStorage.getItem("pictorium_ui_theme"))).toBe("light")
    await page.screenshot({ path: `test-results/theme-light-${width}.png`, fullPage: true, animations: "disabled" })
    await page.reload()
    await expect(page.locator("html")).toHaveAttribute("data-theme", "light")
    await trigger.click()
    await page.getByRole("radio", { name: "Sistema", exact: true }).click()
    await page.emulateMedia({ colorScheme: "dark" })
    await expect(page.locator("html")).toHaveAttribute("data-theme", "dark")
    await page.emulateMedia({ colorScheme: "light" })
    await expect(page.locator("html")).toHaveAttribute("data-theme", "light")
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole("button", { name: /Impostazioni/i }).click()
    if (width < 640) await page.locator("#mobile-settings-category").selectOption("prefs")
    else await page.getByRole("tab", { name: "Preferenze" }).click()
    await expect(page.getByRole("radio", { name: "Chiaro", exact: true })).toBeVisible()
    await page.screenshot({ path: `test-results/theme-settings-${width}.png`, fullPage: true, animations: "disabled" })
    expect(errors).toEqual([])
  })
}

test("light home with a key and poster editor", async ({ page }) => {
  await page.route("**/api/tmdb/19995/images?**", async (route) => {
    const response = await route.fetch()
    const images = await response.json()
    await route.fulfill({ response, json: { ...images, backdrops: [{ ...images.posters[0], file_path: "/mocked/backdrop.jpg", aspect_ratio: 16 / 9, width: 1280, height: 720 }] } })
  })
  await page.addInitScript(() => {
    localStorage.setItem("tmdb_key", "mock-tmdb-key-0000000000")
    localStorage.setItem("pictorium_ui_theme", "light")
  })
  await page.goto("/")
  await expect(page.locator(".home-hero-title")).toBeVisible()
  await expect(page.locator(".home-hero-title .accent-word")).toHaveCSS("filter", "none")
  await expect(page.locator(".home-hero-title .accent-word")).toHaveCSS("-webkit-text-fill-color", "rgb(201, 79, 36)")
  await page.screenshot({ path: "test-results/theme-hero-light.png", fullPage: true, animations: "disabled" })
  const search = page.getByPlaceholder(/cerca/i)
  await expect(search).toHaveCSS("background-color", "rgba(0, 0, 0, 0)")
  await page.getByRole("button", { name: /I miei poster/i }).click()
  const filter = page.locator('.search-shell input')
  await expect(filter).toBeVisible()
  await expect(filter).toHaveCSS("background-color", "rgba(0, 0, 0, 0)")
  await filter.fill("Avatar")
  await expect(filter).toHaveCSS("background-color", "rgba(0, 0, 0, 0)")
  await page.screenshot({ path: "test-results/theme-myposters-light.png", fullPage: true, animations: "disabled" })
  await page.getByRole("button", { name: /I miei poster/i }).click()
  await search.fill("avatar")
  await search.press("Enter")
  await page.getByText(/Avatar/i).first().click()
  await expect(page.getByRole("heading", { name: "Anteprima" })).toBeVisible()
  await page.locator("button.poster-tile").first().click()
  await page.locator("button.poster-tile").first().hover()
  const rotation = page.getByRole("button", { name: "Aggiungi a rotazione", exact: true })
  await expect(rotation.locator("svg")).toHaveCSS("color", "rgb(255, 255, 255)")
  await rotation.hover()
  await expect(rotation.locator("svg")).toHaveCSS("color", "rgb(255, 255, 255)")
  await rotation.click()
  const removeRotation = page.getByRole("button", { name: "Rimuovi da rotazione", exact: true })
  await expect(removeRotation.locator("svg")).toHaveCSS("color", "rgb(255, 255, 255)")
  await removeRotation.click()
  const exclude = page.getByRole("button", { name: "Escludi poster", exact: true })
  await exclude.hover()
  await expect(exclude.locator("svg")).toHaveCSS("color", "rgb(255, 255, 255)")
  await expect(page.locator(".editor-stage img").first()).toBeVisible()
  await expect.poll(() => page.locator(".editor-stage img").first().evaluate((el: HTMLImageElement) => el.complete && el.naturalWidth > 0)).toBe(true)
  await expect(page.locator(".editor-stage").first()).toHaveCSS("background-color", "rgb(12, 12, 14)")
  await expect(page.locator(".editor-preview-fit")).toHaveCSS("background-color", "rgba(0, 0, 0, 0)")
  await expect(page.locator(".editor-preview-fit")).toHaveCSS("box-shadow", "none")
  expect(await page.evaluate(() => localStorage.getItem("pictorium_theme"))).toBe("dark")
  await page.screenshot({ path: "test-results/theme-editor-light.png", fullPage: true, animations: "disabled" })
  await page.getByRole("button", { name: "Orizzontale", exact: true }).click()
  await expect(page.locator(".editor-preview-fit-landscape")).toBeVisible()
  await expect(page.locator(".editor-preview-fit-landscape")).toHaveCSS("background-color", "rgba(0, 0, 0, 0)")
  await expect(page.locator(".editor-preview-fit-landscape")).toHaveCSS("box-shadow", "none")
  await expect.poll(() => page.locator('.editor-stage img[alt="Avatar"]').evaluate((el: HTMLImageElement) => el.complete && el.naturalWidth > el.naturalHeight)).toBe(true)
  await page.locator("button.poster-tile").first().hover()
  await expect(page.getByRole("button", { name: "Aggiungi a rotazione", exact: true }).locator("svg")).toHaveCSS("color", "rgb(255, 255, 255)")
  const excludeBackdrop = page.getByRole("button", { name: "Escludi sfondo", exact: true })
  await excludeBackdrop.hover()
  await expect(excludeBackdrop.locator("svg")).toHaveCSS("color", "rgb(255, 255, 255)")
  await page.screenshot({ path: "test-results/theme-landscape-light.png", fullPage: true, animations: "disabled" })
})

for (const width of [390, 1280]) {
  test(`light settings text at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    await page.addInitScript(() => localStorage.setItem("pictorium_ui_theme", "light"))
    await page.goto("/")
    const logo = page.locator(".header-logo-light:visible").first()
    await expect(logo).toHaveAttribute("src", "/pictorium-light.svg")
    await expect.poll(() => logo.evaluate((el: HTMLImageElement) => el.complete && el.naturalWidth > 0)).toBe(true)
    await page.getByRole("button", { name: /Impostazioni/i }).click()
    for (const [tab, label] of [["badge", "Badge"], ["trasforma", "Trasforma"], ["prefs", "Preferenze"], ["data", "Dati & Cache"]]) {
      if (width < 640) await page.locator("#mobile-settings-category").selectOption(tab)
      else await page.getByRole("tab", { name: label, exact: true }).click()
      const controls = page.getByTestId("settings-controls").filter({ visible: true })
      await expect(controls).toBeVisible()
      const whiteLabels = await controls.evaluate((root) => Array.from(root.querySelectorAll<HTMLElement>("*"))
        .filter((el) => el.checkVisibility() && Array.from(el.childNodes).some((node) => node.nodeType === Node.TEXT_NODE && node.textContent?.trim()))
        .filter((el) => {
          const color = getComputedStyle(el).color.match(/[\d.]+/g)?.slice(0, 3).map(Number)
          return color?.every((value) => value > 235) && !el.closest(".bg-accent-orange, .bg-rose-500, .badge-style-preview")
        })
        .map((el) => ({ text: el.textContent?.trim(), className: el.className })))
      expect(whiteLabels, `White labels in ${tab}`).toEqual([])
      await controls.screenshot({ path: `test-results/settings-${tab}-light-${width}.png`, animations: "disabled" })
    }
  })
}

for (const width of [390, 1280]) {
  test(`light Install Hub text at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    await page.addInitScript(() => {
      localStorage.setItem("pictorium_ui_theme", "light")
      localStorage.setItem("tmdb_key", "mock-tmdb-key-0000000000")
    })
    await page.goto("/")
    await page.getByRole("button", { name: /Installa Hub|^Installa$/ }).click()
    const dialog = page.getByRole("dialog", { name: "Collega Pictorium" })
    await expect(dialog).toBeVisible()
    for (const tab of ["Stremio", "AIOMetadata", "Nuvio"]) {
      await dialog.getByRole("tab", { name: tab, exact: true }).click()
      for (const summary of await dialog.locator("summary:visible").all()) await summary.click()
      const whiteLabels = await dialog.evaluate((root) => Array.from(root.querySelectorAll<HTMLElement>("*"))
        .filter((el) => el.checkVisibility() && Array.from(el.childNodes).some((node) => node.nodeType === Node.TEXT_NODE && node.textContent?.trim()))
        .filter((el) => {
          const color = getComputedStyle(el).color.match(/[\d.]+/g)?.slice(0, 3).map(Number)
          return color?.every((value) => value > 235) && !el.closest(".bg-accent-orange")
        })
        .map((el) => ({ text: el.textContent?.trim(), className: el.className })))
      expect(whiteLabels, `White labels in Install Hub ${tab}`).toEqual([])
      await dialog.screenshot({ path: `test-results/install-${tab}-light-${width}.png`, animations: "disabled" })
    }
  })
}
