import { expect, afterEach, vi } from "vitest"
import { cleanup } from "@testing-library/react"
import * as matchers from "@testing-library/jest-dom/matchers"

import { _resetPinCache } from "@/lib/pin-auth"
import { __resetKey401Cache } from "@/lib/tmdb"

expect.extend(matchers)

// next/font/google non gira fuori da Next (i webfont dei campioni del
// selettore font badge): stub deterministico, solo className. Export
// espliciti: vitest richiede forma statica (niente Proxy).
vi.mock("next/font/google", () => {
  const stub = (name: string) => () => ({ className: `mock-font-${name}` })
  return {
    Barlow_Condensed: stub("Barlow_Condensed"),
    Oswald: stub("Oswald"),
    // Fork: campioni del selettore "Font ebraico".
    Rubik: stub("Rubik"),
    Heebo: stub("Heebo"),
    Karantina: stub("Karantina"),
    Secular_One: stub("Secular_One"),
    Frank_Ruhl_Libre: stub("Frank_Ruhl_Libre"),
  }
})

// I test simulano un'istanza pubblica (route admin aperte senza ADMIN_TOKEN):
// la modalità deve essere esplicita via POSTERIUM_PUBLIC_INSTANCE=1 (vedi auth.ts).
process.env.POSTERIUM_PUBLIC_INSTANCE = "1"

afterEach(() => {
  cleanup()
  vi.unstubAllEnvs()
  _resetPinCache()
  // Stato fetch TMDB (negative cache 401) isolato tra i test: senza, un 401
  // reale (mock esauriti → rete) marchierebbe la chiave per i test seguenti.
  __resetKey401Cache()
  process.env.POSTERIUM_PUBLIC_INSTANCE = "1"
})

const itDict: Record<string, string> = {
  "badge.newMovie": "Nuovo film",
  "badge.newSeries": "Nuova serie",
  "badge.newSeason": "Nuova stagione",
  "badge.newSeasonN": "Nuova S{n}",
  "badge.anime": "Anime",
  "badge.today": "Oggi",
  "badge.movie": "Film",
  "badge.series": "Serie",
  "badge.week": "Settimana",
  "badge.topRated": "Absolute Cinema",
  "badge.miniseries": "Miniserie",
  "badge.returning": "Ritorna",
  "badge.justAddedMovie": "Appena aggiunto",
  "badge.justAddedSeries": "Appena aggiunta",
  "badge.seriesEnded": "Serie conclusa",
  "badge.upcomingRelease": "In uscita {date}",
  "ui.deleteFailed": "Errore nella cancellazione di {count} poster",
  "ui.loadingCatalogs": "Caricamento cataloghi...",
  "ui.confirmDelete": "Eliminare questo poster?",
  "ui.confirmDeleteMsg": "Vuoi eliminare {title}? Non può essere annullata.",
  "ui.confirmDeleteSelected": "Eliminare {count} poster selezionati?",
  "ui.confirmDeleteSelectedMsg": "Questa azione rimuoverà {count} poster selezionati. Non può essere annullata.",
  "ui.retry": "Riprova",
  "ui.close": "Chiudi",
  "ui.back": "Indietro",
  "ui.next": "Avanti",
  "ui.errorDefaultTitle": "Qualcosa è andato storto",
  "ui.errorUnknown": "Errore sconosciuto",
  "ui.onboardingStart": "Inizia!",
  "ui.onboardingSkip": "Salta tutorial",
  "ui.slide": "Slide {n}",
  "ui.addonProxy": "Addon Proxy",
  "ui.scrollLeft": "Scorri a sinistra",
  "ui.scrollRight": "Scorri a destra",
  "ui.statusTmdbUnavailable": "Servizio TMDB non disponibile — alcuni dati potrebbero essere incompleti",
  "ui.rename": "Rinomina",
  "ui.collectionNamePh": "Nome collezione",
  "ui.collectionOptions": "Opzioni collezione",
  "ui.posterWithLogo": "Poster con logo",
  "ui.cleanPoster": "Poster pulito",
  "ui.emptyPostersSub": "Nessun poster salvato. Personalizza un poster dai cataloghi e apparirà qui.",
  "ui.backdrops": "Sfondi",
  "ui.testStremioUrl": "Testa URL Stremio",
  "ui.emptyCollectionTitle": "Nessuna collezione",
  "ui.emptyCollectionSub": "Crea la tua prima collezione per organizzare i poster.",
  "ui.showAllPosters": "Mostra tutti ({count})",
  "ui.noFilteredResultsSub": "Nessun risultato corrisponde a questo filtro.",
  "ui.confirmDeleteCollection": "Elimina collezione",
  "ui.confirmDeleteCollectionMsg": "Eliminare \"{name}\"?",
  "ui.savedOn": "Salvato il",
  "ui.noCollections": "Questo poster non è in nessuna collezione.",
  "ui.openInEditor": "Apri nell'editor",
  "ui.profileLoaded": "Profilo caricato con successo!",
  "ui.loadError": "Errore di caricamento",
  "ui.profileUnlockHint": "Inserisci la password del profilo salvato",
  "ui.profileUnlock": "Accedi",
  "ui.continueWithoutProfile": "Continua senza profilo",
  "ui.proxyTitle": "Generatore Addon Proxy",
  "ui.proxySubtitle": "Inietta i poster di Pictorium in qualsiasi Add-on Stremio",
  "ui.proxyPasteLabel": "Incolla il link manifest.json dell'Add-on originale:",
  "ui.proxyPresets": "Preset rapidi:",
  "ui.proxyGeneratedLabel": "URL Addon Proxy generato:",
  "ui.proxyCopyLink": "Copia Link Proxy",
  "ui.proxyOpenStremio": "Apri su Stremio",
  "ui.proxyHint": "Inserisci l'URL di un add-on per generare il tuo link proxy personalizzato.",
  "ui.profileCreateOrAccess": "Crea o accedi ad un profilo per iniziare",
  "ui.uuidGenerating": "Generazione UUID...",
  "ui.copyUuid": "Copia UUID",
  "ui.aiomLinkTitle": "Link per AIO e custom URL:",
  "ui.aiomLinkDesc": "Usa questo template URL nei campi AIOMetadata o Custom URL della tua app o add-on per visualizzare i poster di Pictorium:",
  "ui.copyUrl": "Copia URL",
  "ui.copyUrlTooltip": "Copia l'URL del poster personalizzato da usare in AIOMetadata o Stremio",
  "ui.existingProfileUuid": "UUID Profilo Esistente",
  "ui.profileYourPassword": "La tua password",
  "ui.loadAndAccess": "Accedi & Carica Profilo",
  "badge.bingeWorthy": "Absolute Cinema",
  "badge.absoluteCinema": "Absolute Cinema",
  "badge.trending": "Di tendenza",
  "badge.trendingSeries": "Serie di tendenza",
  "badge.trendingAnime": "Anime di tendenza",
  "badge.nextEpisode": "Nuovo episodio {date}",
  "badge.highlyRated": "Molto votato",
  "badge.ended": "Conclusa",
  "badge.director": "Di {name}",
  "badge.basedOn.novel": "Dal romanzo",
  "badge.basedOn.comic": "Dal fumetto",
  "badge.basedOn.videogame": "Dal videogioco",
  "badge.basedOn.trueStory": "Tratto da una storia vera",
  "badge.basedOn.story": "Da un racconto",
  "badge.basedOn.theater": "Dal teatro",
  "badge.basedOn.poetry": "Dalla poesia",
  "badge.basedOn.fallback": "Tratto da",
  "badge.winner": "{name}",
  "badge.nominee": "Candidato {name}",
  "award.oscar": "Oscar",
  "award.bafta": "BAFTA",
  "award.golden_globe": "Golden Globe",
  "award.emmy": "Emmy",
  "award.david": "David",
  "award.venezia": "Venezia",
  "award.cannes": "Cannes",
  "franchise.mcu": "MCU",
  "franchise.dc_extended_universe": "DC Extended Universe",
  "franchise.star_wars": "Star Wars",
  "ui.setupPinTitle": "Proteggi il tuo pannello",
  "ui.setupPinSubtitle": "Imposta un PIN di sicurezza per accedere all'editor e salvare modifiche",
  "ui.setupPinSave": "Salva PIN e Inizia",
  "ui.setupPinSaving": "Salvataggio...",
  "ui.setupPinSkip": "Salta questo passaggio",
  "ui.setupPinMinDigits": "Il PIN deve contenere almeno 6 cifre",
  "ui.setupPinStremioNotice": "Manifest e poster Stremio restano aperti",
  "ui.spacesUsedOf": "{used}/{max} spazi ({active} attivi)",
  "ui.spacesUsed": "{used} spazi ({active} attivi)",
  "ui.changelogTitle": "Cosa c'è di nuovo",
  "ui.changelogFeature": "Novità",
  "ui.changelogPerf": "Performance",
  "ui.changelogFix": "Fix",
  "ui.changelogRecent": "Aggiornamenti recenti",
  "ui.hostedByToggle": "Info sponsor: ElfHosted",
  "ui.hostedByTitle": "Ospitato da {name} ❤️",
  "ui.hostedByShared": "Condividi gli slot di rendering e la cache con tutti gli altri.",
  "ui.hostedByElfhosted": "ElfHosted",
  "ui.hostedByDeploy": "Crea la tua istanza privata su ElfHosted",
  "ui.hostedByGuide": "guida gratuita agli addon",
  "ui.hostedByGuideLine": "Nuovo di Stremio? Dai un'occhiata alla {guide}.",
  "ui.hostedByMinimize": "Riduci a icona",
  "ui.starPrompt": "Ti piace Pictorium?",
  "ui.starCta": "Lascia una stella su GitHub",
  "ui.starAria": "Star Pictorium on GitHub",
  "ui.templateUrlTag": "Template URL",
  "ui.epPreviewNote": "È la stessa lista che Stremio riceverà su {path}. Cambia l'ordinamento sopra e verifica qui prima di salvare.",
  "ui.typeMixed": "Misto",
  "ui.typeMovie": "Film",
  "ui.typeSeries": "Serie TV",
  "ui.presetBadgeInvalid": "Il preset non è valido",
  "ui.backupExported": "Backup esportato con successo!",
  "ui.verifyKeyValidity": "Verifica validità chiave",
  "ui.emojiGroupStreaming": "Streaming e Cinema",
  "ui.emojiGroupGenres": "Generi e Temi",
  "ui.emojiGroupPlaces": "Paesi e Simboli",
  "ui.emojiMore": "Altre emoji",
  "ui.githubRepo": "GitHub Repository",
  "ui.discordCommunity": "Discord Community",
  "ui.kofiAria": "Support VPS on Ko-fi ({current}/{target}€)",
  "ui.kofiTitle": "VPS Goal: {current}€ / {target}€ questo mese. Fai una donazione su Ko-fi!",
  "ui.kofiGoal": "VPS Goal",
  "ui.bulkOrderFailed": "Errore su {count} poster",
  "ui.bulkOrderDone": "Ordinamento aggiornato per {count} serie",
  "ui.bestFitLockedSpace": "Best-fit non disponibile: sblocca il tuo profilo per abilitare l'analisi automatica.",
  "ui.bestFitLockedAdmin": "Best-fit protetto: sblocca con il token admin (oppure imposta PICTORIUM_PUBLIC_INSTANCE=1 se istanza senza token).",
  "ui.bestFitHttpError": "Analisi best-fit fallita (HTTP {status})",
  "ui.bestFitNetworkError": "Errore di rete durante l'analisi best-fit",
  "ui.demoGenreDrama": "Dramma",
  "ui.demoGenreAction": "Azione",
  "ui.demoGenreThriller": "Thriller",
  "ui.demoGenreSciFi": "Fantascienza",
  "ui.demoGenreCrime": "Crime",
  "ui.demoGenreAdventure": "Avventura",
  "ui.demoGenreComedy": "Commedia",
  "ui.carousel278": "Badge vetro con effetto liquid glass, tema scuro morbido",
  "ui.carousel155": "Badge bordato elegante, tema chiaro con sfocatura leggera",
  "ui.carousel27205": "Badge a barra con colore accentato arancione, tema scuro",
  "ui.carousel157336": "Badge vetro senza sfocatura, asciutto e luminoso",
  "ui.carousel299534": "Sfocatura intensa con gradiente scuro molto pronunciato",
  "ui.carousel238": "Badge bordato, tema scuro, pulito senza blur extra",
  "ui.carousel11": "Badge colorato genere Fantascienza con sfocatura media",
  "ui.carousel680": "Badge pill con accento rosso, tema scuro minimal",
  "ui.carousel597": "Badge ombra con dramma e gradiente morbido",
  "ui.carousel122": "Badge pill tema scuro con accento dorato",
  "ui.carousel1396": "Ranking badge bordato con genere Crime in primo piano",
  "ui.carousel66732": "Badge colorato genere Fantascienza con leggera sfocatura",
  "ui.carousel1668": "Badge bordato pulito, senza sfocatura, tema chiaro",
  "ui.carousel1399": "Badge a barra con accento blu e sfocatura forte",
  "ui.carousel456": "Badge vetro su tema chiaro, leggero e vivace",
  "ui.carousel76479": "Badge ombra tema scuro, gradiente marcato",
  "ui.carousel82883": "Badge bordato tema scuro genere Fantascienza",
  "ui.carousel60574": "Badge pill tema scuro, essenziale",
  "ui.carousel71912": "Badge colorato con accento viola e sfocatura media",
  "ui.carousel44217": "Ranking badge stile Netflix Top 10, tema scuro e misterioso",
  "ui.carouselTopMovie": "Top {rank} Film",
  "ui.carouselTopSeries": "Top {rank} Serie TV",
  "ui.spaceLabel": "Spazio:",
  "ui.live": "LIVE",
  "ui.previewAria": "Anteprima del poster {title} {logo}",
  "ui.previewWithLogo": "con logo",
  "ui.previewNoLogo": "senza logo",
  "ui.posterSelectionAria": "{title} — selezione poster",
  "ui.customTag": "Custom",
  "ui.standardShort": "Standard",
  "ui.on": "ON",
  "ui.off": "OFF",
  "ui.simklClientId": "Simkl Client ID",
  "ui.fanartProjectKey": "Fanart.tv Project Key",
  "ui.dualTag": "DUAL",
  "badge.top": "TOP",
  "ui.labGradientFrom": "Da",
  "ui.labGradientTo": "A",
  "ui.labShadowBlur": "Sfocatura",
  "ui.labOffsetX": "Offset X",
  "ui.labOffsetY": "Offset Y",
  "ui.labUppercase": "Maiuscolo",
  "ui.labLetterSpacing": "Spaziatura lettere",
  "badge.kdrama": "K-Drama",
  "ui.errPinCurrentWrong": "PIN attuale non corretto",
  "ui.errPinTooShort": "Il nuovo PIN deve avere almeno 6 cifre",
  "ui.errNoPin": "Nessun PIN configurato",
  "ui.errPinMissing": "PIN mancante",
  "ui.errSession": "Errore generazione sessione",
  "ui.errUserLimit": "Limite di spazi raggiunto su questa istanza",
  "ui.errPasswordRequired": "Password obbligatoria (minimo 8 caratteri)",
  "ui.errMultiUserDisabled": "Gli spazi personali sono disattivati su questa istanza",
  "ui.errBodyTooLarge": "Richiesta troppo grande",
  "ui.errInvalidRequest": "Richiesta non valida",
  "ui.errKeyNotSet": "Chiave non impostata",
  "ui.skipToContent": "Vai al contenuto principale",
  "ui.clean": "Clean",
  "ui.passwordLabel": "Password",
  "ui.sourceTmdbCollection": "TMDb Saga",
  "ui.sourceTmdbList": "TMDb Lista",
  "ui.presetsTargetTop": "Top",
  "ui.presetsTargetGenre": "Genere",
  "ui.labTplZoneTop": "Slot in alto",
  "ui.labTplZoneGenre": "Slot genere",
  "ui.labTplTopNetflix": "Nastro Netflix",
  "ui.labTplTopNetflixColor": "Nastro Netflix a colori",
  "ui.labTplTopPlacard": "Targa",
  "ui.labTplTopPill": "Pillola",
  "ui.labTplTopVetro": "Vetro",
  "ui.labTplTopBordo": "Bordo",
  "ui.labTplTopColored": "Nastro colorato",
  "ui.labTplGenreShadow": "Ombra",
  "ui.labTplGenreMinimal": "Minimal",
  "ui.labTplGenrePill": "Pillola",
  "ui.labTplGenreBar": "Barra",
  "ui.labTplGenreColored": "Colorato",
  "ui.labTplGenreBordo": "Bordo",
  "ui.labTplGenreVetro": "Vetro",
  "ui.provider": "Provider",
  "ui.prefsLangRegionTitle": "Lingua e regione",
  "ui.rankCountryGlobal": "il mondo",
  "ui.hebrewFont": "Font ebraico",
  "ui.hebrewFontHint": "Vale per tutto il testo ebraico del poster: riga genere, nastro classifica e titolo sotto il logo. L'arabo resta in Rubik.",
  "ui.posterStyle": "Stile poster",
  "ui.posterStyleClassic": "Classico",
  "ui.posterStyleClassicSub": "Fascia sfocata, genere, anno e voto",
  "ui.posterStyleTag": "Tag",
  "ui.posterStyleTagSub": "Artwork pulito, logo su vetro, tag di stato",
  "ui.tagFade": "Dissolvenza scura dal basso",
  "ui.tagCard": "Logo su pannello di vetro",
  "ui.tagFadeForced": "Senza pannello il logo poggia sempre sulla dissolvenza.",
  "ui.portraitStyle": "Stile poster verticale",
  "ui.landscapeStyle": "Stile poster orizzontale",
  "ui.tagSize": "Dimensione tag",
  "ui.tagOptions": "Opzioni stile tag",
  "ui.landscapeTop10": "Numero Top 10 sui poster orizzontali",
  "ui.landscapeTop10Hint": "Un titolo nella top 10 di oggi (TMDB, solo ciò che è già guardabile) riceve a sinistra una fascia con il suo numero luminoso.",
  "ui.topToday": "Top 10 Oggi",
  "ui.topTodaySub": "Il trending giornaliero di TMDB, solo ciò che è già guardabile — la stessa lista dei numeri sui poster orizzontali.",
  "ui.catalogShape": "Forma dei poster in Stremio/Nuvio",
  "ui.catalogShapeGlobal": "Predefinita",
  "ui.catalogShapePoster": "Verticale",
  "ui.catalogShapeLandscape": "Orizzontale",
  "ui.landscapeTop10Transparent": "Fascia del numero trasparente (sperimentale)",
  "ui.landscapeTop10TransparentHint": "Restano solo il numero e il poster; dietro si vede l'interfaccia dell'app. Questi poster escono in WebP con trasparenza.",
  "ui.neonTint": "Colore del numero",
  "ui.neonTintAuto": "Auto",
  "ui.neonTintWhite": "Bianco",
  "ui.neonTintBlue": "Blu",
  "ui.neonTintCustom": "Colore personalizzato",
  "ui.neonTintHint": "Auto: blu sulla fascia blu notte, neon bianco su quella trasparente (sta bene con qualsiasi colore dell'app).",
  "tag.canceled": "Cancellata",
  "tag.anniversary": "{n} anni",
  "tag.blockbuster": "Campione d'incassi",
  "tag.billion": "Un miliardo d'incassi",
  "tag.hiddenGem": "Perla nascosta",
  "tag.crowdFavorite": "Amato dal pubblico",
  "tag.cult": "Cult",
  "tag.indie": "Indipendente",
  "tag.classicDecade": "Classico anni '{decade}",
  "tag.hitDecade": "Successo anni {decade}",
  "tag.short": "Breve e incisivo",
  "tag.epic": "Epico di {n} ore",
  "tag.fewEpisodes": "Solo {n} episodi",
  "tag.binge": "Da maratona",
  "tag.seasons": "{n} stagioni",
  "tag.halfHour": "Episodi da mezz'ora",
  "tag.g_action": "Azione",
  "tag.g_adventure": "Avventura",
  "tag.g_comedy": "Commedia",
  "tag.g_horror": "Horror",
  "tag.g_scifi": "Fantascienza",
  "tag.g_drama": "Dramma",
  "tag.g_thriller": "Thriller",
  "tag.g_animation": "Animazione",
  "tag.g_documentary": "Documentario",
  "tag.g_crime": "Crime",
  "tag.g_romance": "Romantico",
  "tag.g_fantasy": "Fantasy",
  "tag.g_war": "Guerra",
  "tag.g_history": "Storico",
  "tag.g_music": "Musicale",
  "tag.g_family": "Per famiglie",
  "tag.g_mystery": "Mistero",
  "tag.g_western": "Western",
  "tag.g_romcom": "Commedia romantica",
  "tag.g_actioncomedy": "Action comedy",
  "tag.g_horrorcomedy": "Horror comedy",
  "tag.g_crimedrama": "Crime drama",
  "tag.t_reality": "Reality",
  "tag.t_docuseries": "Docuserie",
  "tag.t_talk": "Talk show",
  "tag.t_anthology": "Antologia",
  "tag.s_truestory": "Tratto da una storia vera",
  "tag.s_book": "Tratto da un libro",
  "tag.s_comic": "Tratto da un fumetto",
  "tag.s_superhero": "Supereroi",
  "tag.s_sequel": "Sequel",
  "tag.s_spinoff": "Spin-off",
  "tag.s_remake": "Remake",
  "tag.s_ai": "Intelligenza artificiale",
  "tag.s_aliens": "Alieni",
  "tag.s_robots": "Robot",
  "tag.s_serialkiller": "Serial killer",
  "tag.s_revenge": "Vendetta",
  "tag.s_spy": "Spionaggio",
  "tag.s_courtroom": "Legal drama",
  "tag.s_ww2": "Seconda guerra mondiale",
  "tag.s_space": "Spazio",
  "tag.s_dystopia": "Distopia",
  "tag.s_endofworld": "Fine del mondo",
  "tag.s_dragons": "Draghi",
  "tag.s_magic": "Magia",
  "tag.s_knights": "Cavalieri",
  "tag.s_sport": "Sport",
  "tag.s_boxing": "Boxe",
  "tag.s_football": "Calcio",
  "tag.s_comingofage": "Formazione",
  "tag.s_highschool": "Liceo",
  "tag.s_christmas": "Film di Natale",
  "tag.s_halloween": "Halloween",
  "tag.s_survival": "Sopravvivenza",
  "tag.s_disaster": "Catastrofe",
  "tag.s_shark": "Squali",
  "tag.s_musician": "Musica e band",
  "tag.s_musical": "Musical",
  "tag.star": "Con {name}",
  "tag.creators": "Dai creatori di {title}",
  "tag.composer": "Musiche di {name}",
  "tag.original": "{network}",
  "tag.st_pixar": "Pixar",
  "tag.st_ghibli": "Studio Ghibli",
  "tag.st_marvel": "Marvel",
  "tag.st_dc": "DC",
  "tag.st_a24": "A24",
  "tag.st_blumhouse": "Blumhouse",
  "tag.st_disney": "Disney",
  "tag.st_dreamworks": "DreamWorks",
  "tag.st_lucasfilm": "Lucasfilm",
  "tag.collection": "Capitolo {n} di {name}",
  "tag.universe": "Universo {name}",
  "tag.il_movie": "Cinema israeliano",
  "tag.il_series": "Serie israeliana",
  "tag.fr_movie": "Cinema francese",
  "tag.es_series": "Serie spagnola",
  "tag.gb": "Produzione britannica",
  "tag.jp_movie": "Cinema giapponese",
  "tag.bollywood": "Bollywood",
  "tag.nordic": "Dramma scandinavo",
  "tag.family": "Per tutta la famiglia",
  "tag.kids": "Per bambini",
}

function mockT(key: string, params?: Record<string, string | number>): string {
  let val = itDict[key] ?? key
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      val = val.replace(`{${k}}`, String(v))
    }
  }
  return val
}

vi.mock("@/lib/i18n", () => ({
  t: mockT,
  createT: () => mockT,
  setLang: vi.fn(),
  dirFor: (l: string) => (l === "he" || l === "ar" ? "rtl" : "ltr"),
  getLang: () => "it",
  isPrefixedKey: (val: string) => val.startsWith("__"),
  badgeKey: (val: string) => val.startsWith("__") ? val.slice(2) : val,
  resolveLabel: (val: string) => mockT(val.startsWith("__") ? val.slice(2) : val),
  resolveLabelFor: (val: string, _lang: string) => mockT(val.startsWith("__") ? val.slice(2) : val),
  isRankKey: () => null,
  BADGE_KEY_PREFIX: "__",
}))
